apiVersion: v1
kind: Service
metadata:
  name: microservice1-phpmyadmin-service
spec:
  selector:
    app: microservice1-phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Use NodePort to expose phpMyAdmin
