apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice1-mysql
  template:
    metadata:
      labels:
        app: microservice1-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: laravel
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: microservice1-mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: microservice1-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: microservice1-mysql-pv-claim
