apply:
	kubectl apply -f deployment.yaml
	kubectl apply -f service.yaml

	kubectl apply -f mysql-pv.yaml
	kubectl apply -f mysql-pv-claim.yaml


delete:
	kubectl delete -f deployment.yaml
	kubectl delete -f service.yaml

	kubectl delete -f mysql-pv.yaml
	kubectl delete -f mysql-pv-claim.yaml


