apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
        - name: microservice2
          imagePullPolicy: Never
          image: microservice2-image:latest
          env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: microservice2-mysql-service # Use the Kubernetes service name
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: laravel
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
          ports:
            - containerPort: 8080
