apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
        - name: microservice1
          imagePullPolicy: Never
          image: microservice1-image:latest
          env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: microservice1-mysql-service # Use the Kubernetes service name
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: laravel
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
          ports:
            - containerPort: 8080
